### ISSUE TITLE
another error!

### ISSUE THREAD

**Issue by flyboyer** [CyberZHG/keras-word-char-embd#2]
**InvalidArgumentError: Reshape cannot infer the missing input size for an empty tensor unless all specified input sizes are non-zero [[Node: Embedding_Char_2/Reshape = Reshape[T=DT_FLOAT, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"](Embedding_Char_Pre_2/embedding_lookup, Embedding_Char_2/Reshape/shape)]]**
run you example of  wapper class,and get this wrong,how to solve it?

**Comment by CyberZHG** [comment]
Thanks, I've updated the examples.
